apiVersion: v1
kind: Service
metadata:
  name: greeter-client
spec:
  ports:
  - name: client 
    port: 8080 
  selector:
    app: greeter-client
  type: NodePort
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: greeter-client
spec:
  selector: 
    matchLabels:
      app: greeter-client
  replicas: 1 
  template:
    metadata:
      labels:
        app: greeter-client
    spec:
      containers:
      - name: greeter-client
        image: greeter-client
        command: ["greeter-client"]
        args: ["--in_k8s=true"]
        imagePullPolicy: Never
        ports:
        - containerPort: 8080 
        env:
        - name: GRPC_VERBOSITY
          value: "debug"
