apiVersion: v1
kind: Service
metadata:
  name: greeter-server
spec:
  ports:
  - name: grpc
    port: 50051 
  selector:
    app: greeter-server
  type: NodePort
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: greeter-server
spec:
  selector: 
    matchLabels:
      app: greeter-server
  replicas: 3
  template:
    metadata:
      labels:
        app: greeter-server
    spec:
      containers:
      - name: greeter-server
        image: greeter-server
        command: ["greeter-server"]
        imagePullPolicy: Never
        ports:
        - containerPort: 50051 
        env:
        - name: GRPC_VERBOSITY
          value: "debug"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
